

export const ORDER_STATUSES = [
  "pending",
  "confirmed",
  "shipped",
  "delivered",
  "canceled",
] as const

export type OrderStatus = (typeof ORDER_STATUSES)[number]

export const FONT_OPTIONS = [
  { value: "Inter", label: "Inter" },
  { value: "Poppins", label: "Poppins" },
  { value: "Roboto", label: "Roboto" },
  { value: "Lato", label: "Lato" },
  { value: "Montserrat", label: "Montserrat" },
  { value: "Open Sans", label: "Open Sans" },
  { value: "Raleway", label: "Raleway" },
  { value: "Playfair Display", label: "Playfair Display" },
  { value: "Merriweather", label: "Merriweather" },
  { value: "Lora", label: "Lora" },
  { value: "Nunito", label: "Nunito" },
  { value: "Nunito Sans", label: "Nunito Sans" },
  { value: "Rubik", label: "Rubik" },
  { value: "Work Sans", label: "Work Sans" },
  { value: "Outfit", label: "Outfit" },
  { value: "DM Sans", label: "DM Sans" },
  { value: "Space Grotesk", label: "Space Grotesk" },
  { value: "Manrope", label: "Manrope" },
  { value: "Plus Jakarta Sans", label: "Plus Jakarta Sans" },
  { value: "Figtree", label: "Figtree" },
  { value: "Sora", label: "Sora" },
  { value: "Albert Sans", label: "Albert Sans" },
  { value: "Karla", label: "Karla" },
  { value: "Cabin", label: "Cabin" },
  { value: "Quicksand", label: "Quicksand" },
  { value: "Mulish", label: "Mulish" },
  { value: "Josefin Sans", label: "Josefin Sans" },
  { value: "Barlow", label: "Barlow" },
  { value: "Source Sans 3", label: "Source Sans 3" },
  { value: "PT Sans", label: "PT Sans" },
  { value: "Oswald", label: "Oswald" },
  { value: "Ubuntu", label: "Ubuntu" },
  { value: "Titillium Web", label: "Titillium Web" },
  { value: "Libre Franklin", label: "Libre Franklin" },
  { value: "Bitter", label: "Bitter" },
  { value: "Crimson Text", label: "Crimson Text" },
  { value: "EB Garamond", label: "EB Garamond" },
  { value: "Libre Baskerville", label: "Libre Baskerville" },
  { value: "PT Serif", label: "PT Serif" },
  { value: "Source Serif 4", label: "Source Serif 4" },
  { value: "Cormorant Garamond", label: "Cormorant Garamond" },
  { value: "Spectral", label: "Spectral" },
  { value: "Noto Sans", label: "Noto Sans" },
  { value: "Noto Serif", label: "Noto Serif" },
  { value: "Cairo", label: "Cairo" },
  { value: "Tajawal", label: "Tajawal" },
  { value: "IBM Plex Sans", label: "IBM Plex Sans" },
  { value: "IBM Plex Serif", label: "IBM Plex Serif" },
  { value: "Fira Sans", label: "Fira Sans" },
  { value: "Kanit", label: "Kanit" },
  { value: "Comfortaa", label: "Comfortaa" },
  { value: "Archivo", label: "Archivo" },
  { value: "Lexend", label: "Lexend" },
  { value: "Exo 2", label: "Exo 2" },
  { value: "Signika", label: "Signika" },
  { value: "Vollkorn", label: "Vollkorn" },
  { value: "Inconsolata", label: "Inconsolata" },
  { value: "JetBrains Mono", label: "JetBrains Mono" },
  { value: "Fira Code", label: "Fira Code" },
] as const

export const BORDER_RADIUS_OPTIONS = [
  { value: "none", label: "None", css: "0px" },
  { value: "sm", label: "Small", css: "4px" },
  { value: "md", label: "Medium", css: "8px" },
  { value: "lg", label: "Large", css: "12px" },
  { value: "xl", label: "Extra Large", css: "16px" },
] as const

export const BUTTON_STYLE_OPTIONS = [
  { value: "filled", label: "Filled" },
  { value: "outline", label: "Outline" },
  { value: "pill", label: "Pill" },
] as const

export const CARD_SHADOW_OPTIONS = [
  { value: "none", label: "None", css: "none" },
  { value: "sm", label: "Small", css: "0 1px 2px 0 rgb(0 0 0 / 0.05)" },
  { value: "md", label: "Medium", css: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)" },
  { value: "lg", label: "Large", css: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)" },
] as const

export const PRODUCT_IMAGE_RATIO_OPTIONS = [
  { value: "square", label: "Square", css: "1/1" },
  { value: "portrait", label: "Portrait", css: "3/4" },
  { value: "landscape", label: "Landscape", css: "4/3" },
] as const

export const LAYOUT_SPACING_OPTIONS = [
  { value: "compact", label: "Compact", gap: "0.5rem", padding: "0.5rem" },
  { value: "normal", label: "Normal", gap: "0.75rem", padding: "0.75rem" },
  { value: "spacious", label: "Spacious", gap: "1.25rem", padding: "1rem" },
] as const

export const COLOR_THEME_PRESETS = [
  {
    id: "classic-store",
    nameKey: "design.presetClassicStore",
    colors: {
      primary_color: "#1D4ED8",
      accent_color: "#2563EB",
      background_color: "#FFFFFF",
      text_color: "#111827",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "trust-green",
    nameKey: "design.presetTrustGreen",
    colors: {
      primary_color: "#15803D",
      accent_color: "#16A34A",
      background_color: "#FFFFFF",
      text_color: "#111827",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "soft-rose",
    nameKey: "design.presetSoftRose",
    colors: {
      primary_color: "#BE185D",
      accent_color: "#E11D48",
      background_color: "#FFF5F6",
      text_color: "#1F2937",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "warm-amber",
    nameKey: "design.presetWarmAmber",
    colors: {
      primary_color: "#B45309",
      accent_color: "#D97706",
      background_color: "#FFFBF5",
      text_color: "#292524",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "ocean-teal",
    nameKey: "design.presetOceanTeal",
    colors: {
      primary_color: "#0F766E",
      accent_color: "#0D9488",
      background_color: "#FFFFFF",
      text_color: "#111827",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "coral-pop",
    nameKey: "design.presetCoralPop",
    colors: {
      primary_color: "#DC2626",
      accent_color: "#F43F5E",
      background_color: "#FFFFFF",
      text_color: "#18181B",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "lavender-chic",
    nameKey: "design.presetLavenderChic",
    colors: {
      primary_color: "#7C3AED",
      accent_color: "#8B5CF6",
      background_color: "#FAFAFF",
      text_color: "#1E1B4B",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "forest-natural",
    nameKey: "design.presetForestNatural",
    colors: {
      primary_color: "#3F6212",
      accent_color: "#65A30D",
      background_color: "#F8FAF5",
      text_color: "#1A2E05",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "midnight-luxe",
    nameKey: "design.presetMidnightLuxe",
    colors: {
      primary_color: "#F59E0B",
      accent_color: "#FBBF24",
      background_color: "#0F172A",
      text_color: "#F1F5F9",
      button_text_color: "#0F172A",
    },
  },
  {
    id: "slate-minimal",
    nameKey: "design.presetSlateMinimal",
    colors: {
      primary_color: "#334155",
      accent_color: "#475569",
      background_color: "#FFFFFF",
      text_color: "#0F172A",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "sunset-market",
    nameKey: "design.presetSunsetMarket",
    colors: {
      primary_color: "#EA580C",
      accent_color: "#F97316",
      background_color: "#FFFCF5",
      text_color: "#431407",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "berry-boutique",
    nameKey: "design.presetBerryBoutique",
    colors: {
      primary_color: "#A21CAF",
      accent_color: "#C026D3",
      background_color: "#FDF4FF",
      text_color: "#4A044E",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "sky-fresh",
    nameKey: "design.presetSkyFresh",
    colors: {
      primary_color: "#0369A1",
      accent_color: "#0284C7",
      background_color: "#F0F9FF",
      text_color: "#0C4A6E",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "mocha-cafe",
    nameKey: "design.presetMochaCafe",
    colors: {
      primary_color: "#78350F",
      accent_color: "#92400E",
      background_color: "#FDF8F4",
      text_color: "#422006",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "mint-clean",
    nameKey: "design.presetMintClean",
    colors: {
      primary_color: "#047857",
      accent_color: "#059669",
      background_color: "#F0FDF4",
      text_color: "#064E3B",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "plum-premium",
    nameKey: "design.presetPlumPremium",
    colors: {
      primary_color: "#6B21A8",
      accent_color: "#7E22CE",
      background_color: "#FAF5FF",
      text_color: "#3B0764",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "honey-gold",
    nameKey: "design.presetHoneyGold",
    colors: {
      primary_color: "#A16207",
      accent_color: "#CA8A04",
      background_color: "#FFFDF5",
      text_color: "#422006",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "deep-navy",
    nameKey: "design.presetDeepNavy",
    colors: {
      primary_color: "#60A5FA",
      accent_color: "#3B82F6",
      background_color: "#0C1222",
      text_color: "#E2E8F0",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "peach-soft",
    nameKey: "design.presetPeachSoft",
    colors: {
      primary_color: "#C2410C",
      accent_color: "#EA580C",
      background_color: "#FFF7ED",
      text_color: "#7C2D12",
      button_text_color: "#FFFFFF",
    },
  },
  {
    id: "charcoal-edge",
    nameKey: "design.presetCharcoalEdge",
    colors: {
      primary_color: "#E4E4E7",
      accent_color: "#A1A1AA",
      background_color: "#18181B",
      text_color: "#FAFAFA",
      button_text_color: "#18181B",
    },
  },
] as const

export const COUNTRIES = [
  { code: "AF", name: "Afghanistan" }, { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" }, { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" }, { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina" }, { code: "AM", name: "Armenia" },
  { code: "AU", name: "Australia" }, { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" }, { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" }, { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" }, { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" }, { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" }, { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" }, { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" }, { code: "BR", name: "Brazil" },
  { code: "BN", name: "Brunei" }, { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" }, { code: "BI", name: "Burundi" },
  { code: "CV", name: "Cabo Verde" }, { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" }, { code: "CA", name: "Canada" },
  { code: "CF", name: "Central African Republic" }, { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" }, { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" }, { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo" }, { code: "CR", name: "Costa Rica" },
  { code: "HR", name: "Croatia" }, { code: "CU", name: "Cuba" },
  { code: "CY", name: "Cyprus" }, { code: "CZ", name: "Czech Republic" },
  { code: "DK", name: "Denmark" }, { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" }, { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" }, { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" }, { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" }, { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" }, { code: "ET", name: "Ethiopia" },
  { code: "FJ", name: "Fiji" }, { code: "FI", name: "Finland" },
  { code: "FR", name: "France" }, { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" }, { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" }, { code: "GH", name: "Ghana" },
  { code: "GR", name: "Greece" }, { code: "GD", name: "Grenada" },
  { code: "GT", name: "Guatemala" }, { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" }, { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" }, { code: "HN", name: "Honduras" },
  { code: "HU", name: "Hungary" }, { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" }, { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" }, { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" }, { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" }, { code: "CI", name: "Ivory Coast" },
  { code: "JM", name: "Jamaica" }, { code: "JP", name: "Japan" },
  { code: "JO", name: "Jordan" }, { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" }, { code: "KI", name: "Kiribati" },
  { code: "KW", name: "Kuwait" }, { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Laos" }, { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" }, { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" }, { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" }, { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" }, { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" }, { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" }, { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" }, { code: "MH", name: "Marshall Islands" },
  { code: "MR", name: "Mauritania" }, { code: "MU", name: "Mauritius" },
  { code: "MX", name: "Mexico" }, { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldova" }, { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" }, { code: "ME", name: "Montenegro" },
  { code: "MA", name: "Morocco" }, { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" }, { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" }, { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" }, { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" }, { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" }, { code: "KP", name: "North Korea" },
  { code: "MK", name: "North Macedonia" }, { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" }, { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" }, { code: "PS", name: "Palestine" },
  { code: "PA", name: "Panama" }, { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" }, { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" }, { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" }, { code: "QA", name: "Qatar" },
  { code: "RO", name: "Romania" }, { code: "RU", name: "Russia" },
  { code: "RW", name: "Rwanda" }, { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "Samoa" }, { code: "SM", name: "San Marino" },
  { code: "ST", name: "Sao Tome and Principe" },
  { code: "SA", name: "Saudi Arabia" }, { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" }, { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" }, { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovakia" }, { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" }, { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" }, { code: "KR", name: "South Korea" },
  { code: "SS", name: "South Sudan" }, { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" }, { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" }, { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" }, { code: "SY", name: "Syria" },
  { code: "TW", name: "Taiwan" }, { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" }, { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" }, { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" }, { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" }, { code: "TR", name: "Turkey" },
  { code: "TM", name: "Turkmenistan" }, { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" }, { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom" }, { code: "US", name: "United States" },
  { code: "UY", name: "Uruguay" }, { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" }, { code: "VA", name: "Vatican City" },
  { code: "VE", name: "Venezuela" }, { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yemen" }, { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
] as const

export type Country = (typeof COUNTRIES)[number]

export const CURRENCIES = [
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م." },
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "CAD", name: "Canadian Dollar", symbol: "CA$" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "MXN", name: "Mexican Peso", symbol: "MX$" },
  { code: "ARS", name: "Argentine Peso", symbol: "AR$" },
  { code: "CLP", name: "Chilean Peso", symbol: "CL$" },
  { code: "COP", name: "Colombian Peso", symbol: "CO$" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
  { code: "DKK", name: "Danish Krone", symbol: "kr" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
  { code: "RON", name: "Romanian Leu", symbol: "lei" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت" },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
  { code: "QAR", name: "Qatari Riyal", symbol: "﷼" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" },
  { code: "BHD", name: "Bahraini Dinar", symbol: "BD" },
  { code: "OMR", name: "Omani Rial", symbol: "﷼" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "JD" },
  { code: "ILS", name: "Israeli Shekel", symbol: "₪" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "₨" },
  { code: "THB", name: "Thai Baht", symbol: "฿" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "TWD", name: "Taiwan Dollar", symbol: "NT$" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
] as const
